# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A = np.zeros((5,5))
print("%d bytes" % (A.size*A.itemsize))

200 bytes


In [ ]:
  A,nbytes

NameError: name 'nbytes' is not defined

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
A = A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1 = np.arange(0,9)
array2 = array1.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array3 = np.array([1,2,0,0,4,0])
np.nonzero(array3)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
imatrix = np.eye(3)
print(imatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
rarray = np.random.random((3,3,3))
print(rarray)

[[[0.66547182 0.38928475 0.13398992]
  [0.47784949 0.31795153 0.83780929]
  [0.97485499 0.22997013 0.7366884 ]]

 [[0.06280104 0.62235692 0.71373543]
  [0.41259499 0.95851791 0.34527116]
  [0.62340564 0.71353189 0.5912254 ]]

 [[0.07112875 0.37432561 0.45668107]
  [0.23042139 0.69785909 0.25153786]
  [0.27693991 0.19064715 0.95554316]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
rarray2 = np.random.random((10,10))
print(rarray2)
min = np.min(array2)
max = np.max(array2)
print(min)
print(max)

[[0.67923556 0.85894457 0.44436855 0.85362701 0.67539375 0.45477567
  0.20740321 0.14869188 0.52455719 0.73809235]
 [0.79011337 0.83250932 0.75103157 0.54259458 0.49545553 0.92146189
  0.09914691 0.83006432 0.66782866 0.16586932]
 [0.17940705 0.88239056 0.75186235 0.39643812 0.12996825 0.48835045
  0.50270024 0.66199112 0.4331893  0.07056977]
 [0.32850995 0.78575001 0.72229675 0.29546454 0.00967858 0.35811003
  0.53902106 0.54938958 0.3066301  0.51664883]
 [0.63610391 0.25947029 0.12173119 0.23940076 0.05889632 0.67232198
  0.3918469  0.10374247 0.87299463 0.05564844]
 [0.51244714 0.08124888 0.41602447 0.57851371 0.89863276 0.34522203
  0.98178453 0.85399846 0.4462315  0.28505637]
 [0.15132126 0.26973207 0.43046331 0.59777377 0.66833438 0.06165589
  0.54182193 0.56904288 0.46037494 0.27674213]
 [0.25723486 0.12446368 0.26921262 0.8519306  0.4793338  0.51134594
  0.49983046 0.46272644 0.27306713 0.46976361]
 [0.80932822 0.30835012 0.61486211 0.03965761 0.13537332 0.78414374
  0.34367812

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
vector = np.random.random(30)
print(vector)
mean = np.mean(vector)
print(mean)

[0.73685204 0.76554642 0.45339092 0.3379278  0.15536976 0.94542191
 0.83616458 0.25875968 0.19985532 0.53155268 0.69196667 0.5973437
 0.56599478 0.3723185  0.77663334 0.62501044 0.15689287 0.70678339
 0.9468272  0.49214544 0.96908559 0.91292944 0.57631663 0.24944151
 0.4581592  0.33977072 0.03131473 0.1578035  0.43129084 0.8771152 ]
0.5385328259123713


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr_14 = np.ones((3,3), dtype = 'int64')
arr_14[1,1] = 0
arr_14

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
# np.diag() 사용

arr_16_1 = np.diag([1,2,3,4], k=-1)
print(arr_16_1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
# 팬시 인덱싱 사용
arr_17_1 = np.zeros((8,8))
arr_17_1[::2, 1::2] = 1
arr_17_1[1::2, ::2] = 1
print(arr_17_1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# np.tile() 사용

arr_17_2 = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(arr_17_2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
import random

arr_19 = np.random.random((5,5))
arr_mean = np.mean(arr_19)
arr_std = np.std(arr_19)
arr_norm = (arr_19-arr_mean)/arr_std

print(arr_norm)
print('평균:', np.mean(arr_norm), '\n표준편차:', np.std(arr_norm))

[[-1.30562942  0.91171924  0.0765419   0.86229817  1.55433902]
 [ 1.04404595 -0.13748417 -0.313455   -0.66330987  1.47437608]
 [-0.20599609  0.5109472  -0.93984888 -1.29813466 -0.17976798]
 [ 0.09162513 -0.4380406   1.46154884 -1.41935323 -1.37398705]
 [-1.27472637 -0.81956173  0.98415573  1.72176594 -0.32406815]]
평균: -1.8429702208777598e-16 
표준편차: 1.0


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
dot_product = np.dot(a,b)
print(dot_product)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.arange(10)
a[3:9] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# 마지막 제외하고 다 가능
Z = np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# array끼리 나누기 불가
print(np.array(0) / np.array(0))

# array 나눗셈에서 몫 구하기 가능
print(np.array(0) // np.array(0))

#
np.array([np.nan]).astype(int).astype(float)

nan
0


<ipython-input-44-9a465e7d8fb0>:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-44-9a465e7d8fb0>:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-44-9a465e7d8fb0>:8: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

np.intersect1d(Z1,Z2)

array([1, 2, 3, 7])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-7-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-07-31', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
import numpy as np

A = np.ones(3)
B = np.ones(3)*2
C = np.ones(3)*3

x = np.add(A,B)
y = np.divide(np.negative(A), 2)
np.multiply(x,y)

# out parameter?

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`[링크 텍스트](https://)

In [ ]:
A = np.random.uniform(0,10,10)
print(A)

# 1.
print(A - A%1) # 나머지 연산자 %
# 2.
print(A // 1) # 몫 반환 //

[1.00174567 8.17585226 9.5797482  6.98586173 9.79498575 4.48958076
 9.84565401 1.90738919 6.72782892 0.22777619]
[1. 8. 9. 6. 9. 4. 9. 1. 6. 0.]
[0.00174567 0.17585226 0.5797482  0.98586173 0.79498575 0.48958076
 0.84565401 0.90738919 0.72782892 0.22777619]
[1. 8. 9. 6. 9. 4. 9. 1. 6. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.zeros((5,5))
A += np.arange(5)
A

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A = np.random.random(10)
A.sort()
A

array([0.16587068, 0.20905328, 0.24174686, 0.36521232, 0.37157625,
       0.44456347, 0.67598672, 0.68229764, 0.72368598, 0.95801738])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
A = np.random.random((10,2))

x = A[:,0] #0열
y = A[:,1] #1열

c = np.sqrt(x**2+y**2) # cartesian coordinates
p = np.arctan2(y,x) # polar coordinates

print(c)
print(p)

[0.91778539 0.80265469 1.06825318 0.76275964 0.91685203 1.18495419
 0.31384611 0.82724163 0.60058445 0.68848754]
[0.6402951  1.51435662 0.45618532 1.16048511 0.50896088 0.64909897
 0.0018731  0.53740633 0.34925377 1.13394858]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
A = np.random.random(10)
A[A.argmax()] = 0
A

# .max() vs. .argmax()

array([0.5589779 , 0.24082885, 0.        , 0.28888828, 0.26028213,
       0.81675643, 0.28887004, 0.07806549, 0.52496833, 0.15623438])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)

X = np.absolute(Z - v)
X.argmin()

# 21st element of Z

21

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, x in np.ndenumerate(Z):
  print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
Z = np.zeros((2,3))
np.put(Z, np.random.choice(range(2*3), 2, replace = False),'6')
print(Z)

[[6. 0. 6.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1
Z = np.random.randint(0,10,(3,3))

np.sort(Z[Z[:,0].argsort()])

array([[0, 1, 6],
       [3, 6, 8],
       [2, 5, 8]])

In [ ]:
# column 2
Z = np.random.randint(0,10,(3,3))

np.sort(Z[Z[:,1].argsort()])

array([[0, 1, 1],
       [1, 2, 8],
       [5, 7, 8]])

In [ ]:
# column 3
Z = np.random.randint(0,10,(3,3))

np.sort(Z[Z[:,2].argsort()])

array([[2, 5, 6],
       [2, 2, 6],
       [1, 8, 9]])