# [개념정리]

## 1. 머신러닝의 개념

- 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 복잡한 조건이나 규칙들이 다양한 형태로 결합하고 변하여 일정한 패턴을 찾기 어려운 경우에 유용
- 분류
  - 지도학습 (Supervised Learning)
  - 비지도학습 (Un-supervised Learning)
  - 강화학습 (Reinforcement Learning)

## 3. 넘파이 (NumPy; Numerical Python)

- 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 빠른 연산 보장 but 파이썬 언어 자체가 가지는 수행 성능의 제약 => C/C++ 기반의 코드 작성 후 넘파이에서 호출하는 방식 (ex. 텐서플로)

### 3.1 넘파이 ndarray 개요

- ndarray: 넘파이의 기반 데이터 타입, 넘파이에서의 다차원 배열 생성 및 다양한 연산 수행에 이용
- np.array(): 인자를 입력 받아 ndarray로 변환
- ndarray.shape(): ndarray의 차원과 크기를 튜플 형태로 나타냄

### 3.2 ndarray의 데이터 타입

- ndarray 내의 데이터값: 숫자, 문자열, 불 등 모두 가능
- ndarray내의 dtype은 같은 것만 가능
- 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경 시 데이터 크기가 더 큰 데이터 타입으로 일괄 변환
- astype()에 인자로 원하는 타입을 문자열로 지정하여 ndarray 내의 dtype 변경 가능

### 3.3 ndarray를 편리하게 생성하기 - arange, zeros, ones

- arange(): array를 range()로 표현; 0부터 함수 인자 값-1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
- zeros(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 뒤 해당 shape을 가진 ndarray를 반환
- ones(): 함수 인자로 휴플 형태의 shape 값을 입력하면 모든 값을 1로 채운 뒤 해당 shape을 가진 ndarray를 반환
- cf. 함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 출력

### 3.4 ndarray의 차원과 크기를 변경하는 reshape()

- ndarray를 특정 차원 및 크기로 변환
- 인자로 -1 사용 시 원래 ndarray와 호환되는 새로운 shape으로 변환 (reshape(-1,1)의 형태로 자주 사용됨 => 2차원, 1칼럼)
- cf. ndarray는 tolist()를 이용해 리스트 자료형으로 변환 가능

### 3.5 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

- cf. 인덱스는 0부터 시작
- cf. 인덱스에 마이너스 기호 사용 시 맨 뒤에서부터 데이터 추출 가능 (-1은 맨 뒤, -2는 맨 뒤에서 두 번째)
- cf. 로우와 칼럼을 넘파이 ndarray에서 표현하는 방식: axis0, axis1 (축 기반의 연산에서 axis 생략 시 axis0 의미)
---
- 단일 값 추출
  - ndarray 객체에 해당하는 위치의 인덱스 값을 []안에 입력
- 슬라이싱
  - [ : ]
  - 다차원에서 한 쪽에만 슬라이싱을 적용하고 다른 쪽 축에는 단일 값 인덱스 적용 가능 (이 경우 1차원으로 변환됨)
  - 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환 (ex. array2d[0] => axis0의 첫 번째 로우 ndarray를 1차원으로 반환)
- 팬시 인덱싱
  - 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식 (ex. array2d[[0,1],2])
- 불린 인덱싱
  - 조건 필터링 & 검색 가능

### 3.6 행렬의 정렬 - sort()와 argsort()

- np.sort()
  - 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort()
  - 원 행렬 자체를 정렬한 형태로 변환
  - 반환 값은 None
- 내림차순 정렬: [::-1] 적용 (ex. np.sort()[::-1])
- 행렬이 2차원 이상일 경우 axis 축 값 설정으로 로우 방향 or 칼럼 방향으로 정렬 가능
---
- np.argsort()
  - 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스가 필요할 때 이용
  - 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
  - 내림차순 정렬: [::-1] 적용 (ex. np.argsort()[::-1])
  - 넘파이의 ndarray는 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 하기 때문에 argsort()의 활용도가 높음

### 3.7 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

- 행렬 내적(행렬 곱)
  - np.dot()
    - np.dot(A, B)
    - [왼쪽 행렬 열 개수 = 오른쪽 행렬 행 개수] 일 때 가능
   
- 전치 행렬
  - transpose()

---

# [필사]

In [2]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [6]:
array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [7]:
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
print('array1: {:0}차원, array2: {:1}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원


In [10]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [11]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [12]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [16]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [19]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [21]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [22]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array5 shape:', array5.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [37]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [38]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [39]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [40]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [41]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [42]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [46]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])
print(array2d[:2, 0].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]
(2,)


In [45]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [50]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [51]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [68]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스 필터링 결과:', array4)

일반 인덱스 필터링 결과: [6 7 8 9]


In [70]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [72]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [73]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [75]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [77]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [78]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 socre_array의 인덱스:', sort_indices_asc)
print('성적 오름차순 정렬 시 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 socre_array의 인덱스: [0 2 4 1 3]
성적 오름차순 정렬 시 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [80]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [81]:
A = np.array([[1,2],
              [3,4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
